# CollectionBuilder 
# Jekyll Digital Collection Generator

# URL variables
# site domain 
url: https://www.lib.uidaho.edu
# location on the domain
# e.g. /digital/hjccc
baseurl: /digital/blackmountaincollege
# CONTENTdm server url
cdm-url: https://digital.ncdcr.gov
# location of code
source-code: https://github.com/CollectionBuilder

# Site settings
title: TEST - Black Mountain College
# header and head metadata
tagline: Test / Demo of CollectionBuilder for Black Mountain College Collection
description: "CollectionBuilder-CONTENTdm is a template for creating digital collection exhibits on top of existing CONTENTdm repositories. This demo features materials from the Frank B. Robinson Papers documenting Psychiana, a religion popular in the 1930s and 40s." 
# Organization branding
organization-name: "State Library of NC"
organization-link: https://digital.ncdcr.gov
organization-logo-banner: https://www.lib.uidaho.edu/media/digital/justdi_logo_sm.png
organization-logo-nav: https://www.lib.uidaho.edu/media/digital/bannerlogo_allwhite.png

# Collection settings
# contentdm collection name 
cdm-collection-id: p249901coll44
# name of metadata file, be sure to also change page_gen data setting!
metadata: blackmountaincollege 
# page gen settings 
# "data" value must be the name of the metadata file
page_gen:
  - data: 'blackmountaincollege'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html'   

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# if present, used to add analytics during build
google-analytics-id: 

# add liquid profiler to id bottlenecks
# profile: true

exclude: [docs/, Rakefile, README.md, LICENSE]

# compress CSS output
sass:
  style: compressed
